#!/bin/sh
if [ -w /var/log ];then
  service=$(basename $(dirname $(pwd)))
  [ -d "/var/log/$service" ] || mkdir -p "/var/log/$service"
  [ -L ./main ] || [ -d ./main ] || ln -s "/var/log/$service" ./main
  [ -L ./current ] || ln -s main/current
  usergroup=$(stat -c "%U:%G" "/var/log/$service")
  if [ "$usergroup" != "daemon:adm" ];then
    chown -R freeswitch:adm "/var/log/$service"
  fi
  exec chpst -u freeswitch:adm svlogd -t ./main
else
  exec svlogd -t ./
fi
